import React, { useState, useEffect } from "react";
import { createRoot } from "react-dom/client";
import { CDSFlex } from "@ciscodesignsystems/cds-react-flex/injected";
import { CDSTable } from "@ciscodesignsystems/cds-react-table/injected";
import { CDSCard } from "@ciscodesignsystems/cds-react-card/injected";
import { POLICY_TABLE_COLUMNS } from "./data/tableColumns";
import rawData from "./data/policyData.json";

import "./index.scss";

function App() {
  const [enableSortColumns, setEnableSortColumns] = useState(false);
  const [enableColumnResizing, setEnableColumnResizing] = useState(false);

  useEffect(() => {
    const shouldEnableSortColumns = false;
    setEnableSortColumns(shouldEnableSortColumns);
  }, []);

  useEffect(() => {
    const shouldEnableColumnResizing =
      localStorage.getItem("enableColumnResizing") === "true";
    setEnableColumnResizing(shouldEnableColumnResizing);
  }, []);

  return (
    <CDSFlex direction="column" gap="medium">
      <h2>Policy Management</h2>
      <CDSCard status="default">
        <CDSTable
          columns={POLICY_TABLE_COLUMNS}
          data={rawData}
          // column sorting
          enableSortColumns
          // column resizing
          enableColumnResizing
          columnResizeMode="onChange"
        />
      </CDSCard>
      <CDSCard>
        <CDSTable
          
          columns={[
            {
              accessorKey: "firstName",
              header: "First Name",
              id: "firstName",
              meta: {
                align: "left",
                columnVisibilityFilterLabel: "First Name",
                filterKey: "firstName",
              },
            },
            {
              accessorKey: "middleInitial",
              header: "M.",
              id: "middleInitial",
              meta: {
                align: "left",
                columnVisibilityFilterLabel: "Middle Initial",
                filterKey: "middleInitial",
              },
            },
            {
              accessorKey: "lastName",
              header:
                "Last Name: This column contains the last name or family name of an individual, which is typically inherited and shared by family members. The last name is used as a primary surname to distinguish individuals within a community or society, often appearing on official documents.",
              id: "lastName",
              maxSize: 200,
              meta: {
                align: "left",
                columnVisibilityFilterLabel: "Last Name",
                filterKey: "lastname",
              },
              minSize: 200,
              size: 200,
            },
            {
              accessorKey: "email",
              enableHiding: false,
              filterFn: function SG() {},
              header: "Email",
              id: "email",
              maxSize: 350,
              meta: {
                align: "left",
                columnVisibilityFilterLabel: "Email",
                filterKey: "email",
              },
            },
            {
              accessorKey: "ip",
              header:
                "IP Address: The unique identifier for a device or network interface in a network. This string is used to route data packets across the internet or local network, and it plays a crucial role in the operation of any networked system. Each IP address is associated with either a public or private network.",
              id: "ip",
              meta: {
                align: "left",
                columnVisibilityFilterLabel: "IP",
                dataType: "networking",
                filterKey: "ip",
              },
            },
            {
              accessorKey: "live",
              cell: function SG() {},
              enableSorting: false,
              header:
                'Live Status: Indicates whether the service, device, or application is currently active and operational, or if it is down. This column helps determine the real-time status of various entities in the system, showing whether they are "live" or "inactive".',
              id: "live",
              meta: {
                align: "center",
                columnVisibilityFilterLabel: "Live",
                disableFilter: true,
              },
            },
            {
              accessorKey: "usage",
              cell: function SG() {},
              filterFn: function SG() {},
              header: "Usage",
              id: "usage",
              meta: {
                align: "right",
                columnVisibilityFilterLabel: "Usage",
                filterKey: "usage",
              },
            },
          ]}
          data={[
            {
              email: "Maurine_Grant71@gmail.com",
              firstName: "Maurine",
              id: 0,
              ip: "184.125.108.199",
              lastName: "Grant",
              live: true,
              middleInitial: "P.",
              usage: undefined,
            },
            {
              email: "Hank.McClure@gmail.com",
              firstName: "Hank",
              id: 1,
              ip: "87.160.186.82",
              lastName: "McClure",
              live: false,
              middleInitial: "N.",
              usage: undefined,
            },
            {
              email: "Deja_Powlowski18@yahoo.com",
              firstName: "Deja",
              id: 2,
              ip: "112.44.21.136",
              lastName: "Powlowski",
              live: true,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Juvenal_Nicolas@hotmail.com",
              firstName: "Juvenal",
              id: 3,
              ip: "189.156.91.184",
              lastName: "Nicolas",
              live: false,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Enoch29@gmail.com",
              firstName: "Enoch",
              id: 4,
              ip: "252.161.196.23",
              lastName: "Hettinger",
              live: true,
              middleInitial: "N.",
              usage: undefined,
            },
            {
              email: "Hortense42@yahoo.com",
              firstName: "Hortense",
              id: 5,
              ip: "19.79.227.109",
              lastName: "Keeling",
              live: true,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Skye_Welch@yahoo.com",
              firstName: "Skye",
              id: 6,
              ip: "221.234.64.27",
              lastName: "Welch",
              live: false,
              middleInitial: "N.",
              usage: 5465133,
            },
            {
              email: "Jerome54@yahoo.com",
              firstName: "Jerome",
              id: 7,
              ip: "110.87.2.77",
              lastName: "Feest",
              live: false,
              middleInitial: "T.",
              usage: 4671487,
            },
            {
              email: "Hayley.Parker@hotmail.com",
              firstName: "Hayley",
              id: 8,
              ip: "172.135.215.44",
              lastName: "Parker",
              live: false,
              middleInitial: "N.",
              usage: 8254625,
            },
            {
              email: "Emely49@gmail.com",
              firstName: "Emely",
              id: 9,
              ip: "146.54.24.133",
              lastName: "Toy",
              live: true,
              middleInitial: "R.",
              usage: undefined,
            },
            {
              email: "Carolanne15@gmail.com",
              firstName: "Carolanne",
              id: 10,
              ip: "195.178.27.81",
              lastName: "VonRueden",
              live: true,
              middleInitial: "M.",
              usage: 9045355,
            },
            {
              email: "Mathias_Luettgen@yahoo.com",
              firstName: "Mathias",
              id: 11,
              ip: "218.215.182.91",
              lastName: "Luettgen",
              live: false,
              middleInitial: "S.",
              usage: undefined,
            },
            {
              email: "Alta_Haag@yahoo.com",
              firstName: "Alta",
              id: 12,
              ip: "142.254.1.91",
              lastName: "Haag",
              live: true,
              middleInitial: "C.",
              usage: undefined,
            },
            {
              email: "Nora.Medhurst29@hotmail.com",
              firstName: "Nora",
              id: 13,
              ip: "102.195.61.94",
              lastName: "Medhurst",
              live: false,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Schuyler84@yahoo.com",
              firstName: "Schuyler",
              id: 14,
              ip: "75.141.209.218",
              lastName: "Barrows",
              live: true,
              middleInitial: "K.",
              usage: 5121834,
            },
            {
              email: "Gerhard_Halvorson@yahoo.com",
              firstName: "Gerhard",
              id: 15,
              ip: "148.148.133.79",
              lastName: "Halvorson",
              live: false,
              middleInitial: "N.",
              usage: 4814803,
            },
            {
              email: "Thad98@hotmail.com",
              firstName: "Thad",
              id: 16,
              ip: "144.65.183.144",
              lastName: "O'Keefe",
              live: true,
              middleInitial: "T.",
              usage: 4252452,
            },
            {
              email: "Rae_Huels7@yahoo.com",
              firstName: "Rae",
              id: 17,
              ip: "16.109.1.52",
              lastName: "Huels",
              live: true,
              middleInitial: "F.",
              usage: 7811698,
            },
            {
              email: "Iva29@gmail.com",
              firstName: "Iva",
              id: 18,
              ip: "209.237.61.145",
              lastName: "Lowe",
              live: false,
              middleInitial: "S.",
              usage: undefined,
            },
            {
              email: "Jacynthe.Romaguera@hotmail.com",
              firstName: "Jacynthe",
              id: 19,
              ip: "106.181.65.214",
              lastName: "Romaguera",
              live: false,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Cassandre.Sauer@gmail.com",
              firstName: "Cassandre",
              id: 20,
              ip: "227.128.178.103",
              lastName: "Sauer",
              live: false,
              middleInitial: "R.",
              usage: 3639641,
            },
            {
              email: "Chet.Beahan@hotmail.com",
              firstName: "Chet",
              id: 21,
              ip: "43.237.14.192",
              lastName: "Beahan",
              live: false,
              middleInitial: "J.",
              usage: 6520855,
            },
            {
              email: "Kiley_Rolfson20@gmail.com",
              firstName: "Kiley",
              id: 22,
              ip: "210.157.232.236",
              lastName: "Rolfson",
              live: false,
              middleInitial: "E.",
              usage: undefined,
            },
            {
              email: "Arlene.Kuhic@hotmail.com",
              firstName: "Arlene",
              id: 23,
              ip: "108.222.143.110",
              lastName: "Kuhic",
              live: false,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Jermaine_Kunze@yahoo.com",
              firstName: "Jermaine",
              id: 24,
              ip: "144.149.108.52",
              lastName: "Kunze",
              live: false,
              middleInitial: "B.",
              usage: 4498806,
            },
            {
              email: "Mikel.Hoeger47@hotmail.com",
              firstName: "Mikel",
              id: 25,
              ip: "179.31.247.138",
              lastName: "Hoeger",
              live: false,
              middleInitial: "D.",
              usage: 7805640,
            },
            {
              email: "Annabelle.OKeefe66@gmail.com",
              firstName: "Annabelle",
              id: 26,
              ip: "250.12.82.202",
              lastName: "O'Keefe",
              live: false,
              middleInitial: "A.",
              usage: 9775591,
            },
            {
              email: "Joshuah.Kautzer5@hotmail.com",
              firstName: "Joshuah",
              id: 27,
              ip: "123.206.46.154",
              lastName: "Kautzer",
              live: false,
              middleInitial: "E.",
              usage: undefined,
            },
            {
              email: "Madge.Rogahn@yahoo.com",
              firstName: "Madge",
              id: 28,
              ip: "253.127.60.44",
              lastName: "Rogahn",
              live: true,
              middleInitial: "R.",
              usage: undefined,
            },
            {
              email: "Markus.Lehner@yahoo.com",
              firstName: "Markus",
              id: 29,
              ip: "128.125.80.209",
              lastName: "Lehner",
              live: false,
              middleInitial: "S.",
              usage: undefined,
            },
            {
              email: "Brennan4@yahoo.com",
              firstName: "Brennan",
              id: 30,
              ip: "206.76.229.104",
              lastName: "Cartwright",
              live: false,
              middleInitial: "C.",
              usage: undefined,
            },
            {
              email: "Gage_Hayes43@yahoo.com",
              firstName: "Gage",
              id: 31,
              ip: "96.19.24.46",
              lastName: "Hayes",
              live: false,
              middleInitial: "E.",
              usage: 8556501,
            },
            {
              email: "Jovani.Kris79@gmail.com",
              firstName: "Jovani",
              id: 32,
              ip: "152.53.63.113",
              lastName: "Kris",
              live: true,
              middleInitial: "S.",
              usage: undefined,
            },
            {
              email: "Michel91@hotmail.com",
              firstName: "Michel",
              id: 33,
              ip: "68.13.128.97",
              lastName: "Jenkins",
              live: false,
              middleInitial: "E.",
              usage: 2597668,
            },
            {
              email: "Kendall.Cole@yahoo.com",
              firstName: "Kendall",
              id: 34,
              ip: "54.251.26.147",
              lastName: "Cole",
              live: false,
              middleInitial: "T.",
              usage: undefined,
            },
            {
              email: "Lolita53@yahoo.com",
              firstName: "Lolita",
              id: 35,
              ip: "121.41.140.152",
              lastName: "Jacobs",
              live: false,
              middleInitial: "E.",
              usage: 7243709,
            },
            {
              email: "Elda_Murray65@gmail.com",
              firstName: "Elda",
              id: 36,
              ip: "4.244.32.122",
              lastName: "Murray",
              live: true,
              middleInitial: "E.",
              usage: undefined,
            },
            {
              email: "Shana.Schiller67@hotmail.com",
              firstName: "Shana",
              id: 37,
              ip: "223.179.91.117",
              lastName: "Schiller",
              live: true,
              middleInitial: "A.",
              usage: 3978873,
            },
            {
              email: "Ansley1@yahoo.com",
              firstName: "Ansley",
              id: 38,
              ip: "138.184.20.1",
              lastName: "Zulauf",
              live: true,
              middleInitial: "B.",
              usage: 6808118,
            },
            {
              email: "Arturo.Fahey@hotmail.com",
              firstName: "Arturo",
              id: 39,
              ip: "90.138.183.145",
              lastName: "Fahey",
              live: true,
              middleInitial: "G.",
              usage: undefined,
            },
            {
              email: "Dangelo29@yahoo.com",
              firstName: "D'angelo",
              id: 40,
              ip: "19.107.228.115",
              lastName: "Marquardt",
              live: false,
              middleInitial: "S.",
              usage: undefined,
            },
            {
              email: "Tony_McGlynn33@hotmail.com",
              firstName: "Tony",
              id: 41,
              ip: "128.161.0.84",
              lastName: "McGlynn",
              live: false,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Sid70@gmail.com",
              firstName: "Sid",
              id: 42,
              ip: "104.225.95.138",
              lastName: "Rempel",
              live: true,
              middleInitial: "S.",
              usage: undefined,
            },
            {
              email: "Werner.Kovacek35@hotmail.com",
              firstName: "Werner",
              id: 43,
              ip: "89.233.99.102",
              lastName: "Kovacek",
              live: true,
              middleInitial: "A.",
              usage: 1659565,
            },
            {
              email: "Gino.Jacobson90@gmail.com",
              firstName: "Gino",
              id: 44,
              ip: "165.89.76.162",
              lastName: "Jacobson",
              live: true,
              middleInitial: "G.",
              usage: undefined,
            },
            {
              email: "Dorian.DuBuque@yahoo.com",
              firstName: "Dorian",
              id: 45,
              ip: "106.225.197.210",
              lastName: "DuBuque",
              live: true,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Melyna33@hotmail.com",
              firstName: "Melyna",
              id: 46,
              ip: "23.138.154.148",
              lastName: "Williamson",
              live: false,
              middleInitial: "J.",
              usage: 4827153,
            },
            {
              email: "Antonina_Parisian21@hotmail.com",
              firstName: "Antonina",
              id: 47,
              ip: "129.71.21.189",
              lastName: "Parisian",
              live: true,
              middleInitial: "L.",
              usage: undefined,
            },
            {
              email: "Keira11@gmail.com",
              firstName: "Keira",
              id: 48,
              ip: "191.129.199.113",
              lastName: "Harvey",
              live: false,
              middleInitial: "M.",
              usage: 5760995,
            },
            {
              email: "Chris_Johnston23@hotmail.com",
              firstName: "Chris",
              id: 49,
              ip: "34.85.45.244",
              lastName: "Johnston",
              live: true,
              middleInitial: "R.",
              usage: undefined,
            },
            {
              email: "Mae.Rutherford@hotmail.com",
              firstName: "Mae",
              id: 50,
              ip: "132.120.105.207",
              lastName: "Rutherford",
              live: false,
              middleInitial: "K.",
              usage: undefined,
            },
            {
              email: "Maria.Abshire@gmail.com",
              firstName: "Maria",
              id: 51,
              ip: "109.241.33.125",
              lastName: "Abshire",
              live: false,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Dominique.Hessel@hotmail.com",
              firstName: "Dominique",
              id: 52,
              ip: "71.52.238.123",
              lastName: "Hessel",
              live: false,
              middleInitial: "R.",
              usage: 2047238,
            },
            {
              email: "Jasper_Bernhard48@yahoo.com",
              firstName: "Jasper",
              id: 53,
              ip: "108.113.148.9",
              lastName: "Bernhard",
              live: true,
              middleInitial: "S.",
              usage: undefined,
            },
            {
              email: "Alize_Hartmann80@hotmail.com",
              firstName: "Alize",
              id: 54,
              ip: "94.42.156.197",
              lastName: "Hartmann",
              live: false,
              middleInitial: "H.",
              usage: undefined,
            },
            {
              email: "Janessa.Walsh50@gmail.com",
              firstName: "Janessa",
              id: 55,
              ip: "123.76.236.243",
              lastName: "Walsh",
              live: false,
              middleInitial: "B.",
              usage: undefined,
            },
            {
              email: "Ray_Hand@yahoo.com",
              firstName: "Ray",
              id: 56,
              ip: "65.14.21.98",
              lastName: "Hand",
              live: false,
              middleInitial: "N.",
              usage: 9890466,
            },
            {
              email: "Mozelle2@yahoo.com",
              firstName: "Mozelle",
              id: 57,
              ip: "244.4.26.121",
              lastName: "Collins",
              live: true,
              middleInitial: "D.",
              usage: undefined,
            },
            {
              email: "Rosalind_Torphy@gmail.com",
              firstName: "Rosalind",
              id: 58,
              ip: "222.150.71.25",
              lastName: "Torphy",
              live: false,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Autumn_Mann35@gmail.com",
              firstName: "Autumn",
              id: 59,
              ip: "105.125.169.155",
              lastName: "Mann",
              live: true,
              middleInitial: "S.",
              usage: 7215319,
            },
            {
              email: "Adaline15@yahoo.com",
              firstName: "Adaline",
              id: 60,
              ip: "181.232.236.101",
              lastName: "Berge",
              live: false,
              middleInitial: "C.",
              usage: undefined,
            },
            {
              email: "Janessa13@hotmail.com",
              firstName: "Janessa",
              id: 61,
              ip: "197.42.30.156",
              lastName: "Monahan",
              live: true,
              middleInitial: "G.",
              usage: 8846224,
            },
            {
              email: "Davon.Purdy@yahoo.com",
              firstName: "Davon",
              id: 62,
              ip: "154.255.232.10",
              lastName: "Purdy",
              live: true,
              middleInitial: "C.",
              usage: undefined,
            },
            {
              email: "Luna.Batz@hotmail.com",
              firstName: "Luna",
              id: 63,
              ip: "84.22.25.166",
              lastName: "Batz",
              live: false,
              middleInitial: "K.",
              usage: undefined,
            },
            {
              email: "Mossie_Pagac13@gmail.com",
              firstName: "Mossie",
              id: 64,
              ip: "133.156.13.252",
              lastName: "Pagac",
              live: true,
              middleInitial: "S.",
              usage: 1225492,
            },
            {
              email: "Steve_Fadel33@gmail.com",
              firstName: "Steve",
              id: 65,
              ip: "225.72.235.99",
              lastName: "Fadel",
              live: false,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Keven.Maggio@gmail.com",
              firstName: "Keven",
              id: 66,
              ip: "217.189.32.204",
              lastName: "Maggio",
              live: true,
              middleInitial: "R.",
              usage: undefined,
            },
            {
              email: "Raquel78@hotmail.com",
              firstName: "Raquel",
              id: 67,
              ip: "234.224.132.220",
              lastName: "Yost",
              live: true,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Halie_Gutmann30@yahoo.com",
              firstName: "Halie",
              id: 68,
              ip: "101.190.122.36",
              lastName: "Gutmann",
              live: true,
              middleInitial: "R.",
              usage: 9383756,
            },
            {
              email: "Keeley.Fisher@gmail.com",
              firstName: "Keeley",
              id: 69,
              ip: "233.199.195.133",
              lastName: "Fisher",
              live: false,
              middleInitial: "H.",
              usage: 7082136,
            },
            {
              email: "Alexys69@gmail.com",
              firstName: "Alexys",
              id: 70,
              ip: "144.3.186.7",
              lastName: "Wunsch",
              live: true,
              middleInitial: "S.",
              usage: 6809633,
            },
            {
              email: "Americo_Bruen@hotmail.com",
              firstName: "Americo",
              id: 71,
              ip: "235.9.52.139",
              lastName: "Bruen",
              live: true,
              middleInitial: "C.",
              usage: 7587939,
            },
            {
              email: "Sage_Mante16@gmail.com",
              firstName: "Sage",
              id: 72,
              ip: "91.136.93.98",
              lastName: "Mante",
              live: true,
              middleInitial: "B.",
              usage: 2358731,
            },
            {
              email: "Delores_OConnell@gmail.com",
              firstName: "Delores",
              id: 73,
              ip: "8.73.36.200",
              lastName: "O'Connell",
              live: true,
              middleInitial: "B.",
              usage: 1873538,
            },
            {
              email: "Dorian87@hotmail.com",
              firstName: "Dorian",
              id: 74,
              ip: "72.229.247.94",
              lastName: "Lang",
              live: false,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Saul80@hotmail.com",
              firstName: "Saul",
              id: 75,
              ip: "206.187.116.154",
              lastName: "McLaughlin",
              live: true,
              middleInitial: "R.",
              usage: 7838196,
            },
            {
              email: "Mike51@gmail.com",
              firstName: "Mike",
              id: 76,
              ip: "189.202.187.62",
              lastName: "Rau",
              live: true,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Jamel_Kerluke@hotmail.com",
              firstName: "Jamel",
              id: 77,
              ip: "140.123.7.112",
              lastName: "Kerluke",
              live: false,
              middleInitial: "S.",
              usage: 4715564,
            },
            {
              email: "Orpha.Abernathy77@yahoo.com",
              firstName: "Orpha",
              id: 78,
              ip: "57.90.96.194",
              lastName: "Abernathy",
              live: false,
              middleInitial: "P.",
              usage: 1958441,
            },
            {
              email: "Madison.MacGyver@yahoo.com",
              firstName: "Madison",
              id: 79,
              ip: "247.215.8.235",
              lastName: "MacGyver",
              live: false,
              middleInitial: "N.",
              usage: undefined,
            },
            {
              email: "Cassidy53@hotmail.com",
              firstName: "Cassidy",
              id: 80,
              ip: "62.238.31.225",
              lastName: "Romaguera",
              live: true,
              middleInitial: "E.",
              usage: 9991794,
            },
            {
              email: "Giovanny51@gmail.com",
              firstName: "Giovanny",
              id: 81,
              ip: "90.141.244.176",
              lastName: "O'Kon",
              live: false,
              middleInitial: "K.",
              usage: 6330164,
            },
            {
              email: "Drew.Kassulke65@yahoo.com",
              firstName: "Drew",
              id: 82,
              ip: "92.50.40.25",
              lastName: "Kassulke",
              live: false,
              middleInitial: "N.",
              usage: undefined,
            },
            {
              email: "Tyler.Welch43@yahoo.com",
              firstName: "Tyler",
              id: 83,
              ip: "57.192.205.118",
              lastName: "Welch",
              live: true,
              middleInitial: "G.",
              usage: undefined,
            },
            {
              email: "Dejuan99@hotmail.com",
              firstName: "Dejuan",
              id: 84,
              ip: "29.153.29.164",
              lastName: "Kautzer",
              live: true,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Sandra27@yahoo.com",
              firstName: "Sandra",
              id: 85,
              ip: "167.183.195.165",
              lastName: "Waelchi",
              live: true,
              middleInitial: "R.",
              usage: undefined,
            },
            {
              email: "Jeromy_Shields@hotmail.com",
              firstName: "Jeromy",
              id: 86,
              ip: "253.149.185.132",
              lastName: "Shields",
              live: true,
              middleInitial: "B.",
              usage: 8275256,
            },
            {
              email: "Norval95@gmail.com",
              firstName: "Norval",
              id: 87,
              ip: "199.127.202.84",
              lastName: "Breitenberg",
              live: true,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Freeda34@gmail.com",
              firstName: "Freeda",
              id: 88,
              ip: "123.1.119.108",
              lastName: "Schneider",
              live: false,
              middleInitial: "F.",
              usage: 4177418,
            },
            {
              email: "Richmond.Daniel@gmail.com",
              firstName: "Richmond",
              id: 89,
              ip: "218.86.19.198",
              lastName: "Daniel",
              live: false,
              middleInitial: "S.",
              usage: 4470524,
            },
            {
              email: "Jarrod_Strosin29@yahoo.com",
              firstName: "Jarrod",
              id: 90,
              ip: "228.186.64.3",
              lastName: "Strosin",
              live: false,
              middleInitial: "R.",
              usage: 9027658,
            },
            {
              email: "Shana_Bergnaum@yahoo.com",
              firstName: "Shana",
              id: 91,
              ip: "159.54.171.241",
              lastName: "Bergnaum",
              live: false,
              middleInitial: "N.",
              usage: 7193562,
            },
            {
              email: "Sabrina_Prosacco@gmail.com",
              firstName: "Sabrina",
              id: 92,
              ip: "214.208.184.220",
              lastName: "Prosacco",
              live: false,
              middleInitial: "S.",
              usage: 5056512,
            },
            {
              email: "Beau.Ondricka@hotmail.com",
              firstName: "Beau",
              id: 93,
              ip: "205.248.246.71",
              lastName: "Ondricka",
              live: false,
              middleInitial: "G.",
              usage: undefined,
            },
            {
              email: "Anthony.Leannon@hotmail.com",
              firstName: "Anthony",
              id: 94,
              ip: "192.86.236.144",
              lastName: "Leannon",
              live: false,
              middleInitial: "J.",
              usage: undefined,
            },
            {
              email: "Sheridan.Rogahn@gmail.com",
              firstName: "Sheridan",
              id: 95,
              ip: "101.134.215.196",
              lastName: "Rogahn",
              live: true,
              middleInitial: "R.",
              usage: undefined,
            },
            {
              email: "Libby_Kuvalis@yahoo.com",
              firstName: "Libby",
              id: 96,
              ip: "87.137.173.229",
              lastName: "Kuvalis",
              live: true,
              middleInitial: "A.",
              usage: undefined,
            },
            {
              email: "Ulices.Volkman@hotmail.com",
              firstName: "Ulices",
              id: 97,
              ip: "131.98.37.71",
              lastName: "Volkman",
              live: false,
              middleInitial: "R.",
              usage: undefined,
            },
            {
              email: "Mae_Hane43@hotmail.com",
              firstName: "Mae",
              id: 98,
              ip: "20.159.253.141",
              lastName: "Hane",
              live: true,
              middleInitial: "F.",
              usage: 7216785,
            },
            {
              email: "Wendy.Roob@yahoo.com",
              firstName: "Wendy",
              id: 99,
              ip: "202.231.9.52",
              lastName: "Roob",
              live: true,
              middleInitial: "M.",
              usage: undefined,
            },
          ]}
          enableColumnResizing
          enableSortColumns
        ></CDSTable>
      </CDSCard>
    </CDSFlex>
  );
}

const container = document.getElementById("root");
const root = createRoot(container);
root.render(<App />);
